### ISSUE TITLE
[Improve]When I have 400 following, Running is block.

### ISSUE THREAD

**Issue by yangwenmai** [gaocegege/scala-github-relationship#3]
The problem is as stated in the title.

**Comment by gaocegege** [comment]
It is not blocked, it is just slow.. I have 500+ and it works well.

**Comment by yangwenmai** [comment]
Sometime It has error , e.g

```

[error] (run-main-0) java.io.IOException: Parse exception converting JSON to object
java.io.IOException: Parse exception converting JSON to object
	at org.eclipse.egit.github.core.client.GitHubClient.parseJson(GitHubClient.java:424)
	at org.eclipse.egit.github.core.client.GitHubClient.getBody(GitHubClient.java:529)
	at org.eclipse.egit.github.core.client.GitHubClient.get(GitHubClient.java:736)
	at org.eclipse.egit.github.core.client.PageIterator.next(PageIterator.java:173)
	at org.eclipse.egit.github.core.service.GitHubService.getAll(GitHubService.java:151)
	at org.eclipse.egit.github.core.service.UserService.getFollowing(UserService.java:301)
	at github.Github.getFollowees(github.scala:37)
	at github.GithubNetwork$$anonfun$InitEdges$1.apply(githubnetwork.scala:115)
	at github.GithubNetwork$$anonfun$InitEdges$1.apply(githubnetwork.scala:109)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
	at github.GithubNetwork.InitEdges(githubnetwork.scala:109)
	at Main$.main(main.scala:27)
	at Main.main(main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: com.google.gson.JsonSyntaxException: javax.net.ssl.SSLException: SSL peer shut down incorrectly
	at com.google.gson.Gson.fromJson(Gson.java:809)
	at com.google.gson.Gson.fromJson(Gson.java:761)
	at org.eclipse.egit.github.core.client.GitHubClient.parseJson(GitHubClient.java:422)
	at org.eclipse.egit.github.core.client.GitHubClient.getBody(GitHubClient.java:529)
	at org.eclipse.egit.github.core.client.GitHubClient.get(GitHubClient.java:736)
	at org.eclipse.egit.github.core.client.PageIterator.next(PageIterator.java:173)
	at org.eclipse.egit.github.core.service.GitHubService.getAll(GitHubService.java:151)
	at org.eclipse.egit.github.core.service.UserService.getFollowing(UserService.java:301)
	at github.Github.getFollowees(github.scala:37)
	at github.GithubNetwork$$anonfun$InitEdges$1.apply(githubnetwork.scala:115)
	at github.GithubNetwork$$anonfun$InitEdges$1.apply(githubnetwork.scala:109)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
	at github.GithubNetwork.InitEdges(githubnetwork.scala:109)
	at Main$.main(main.scala:27)
	at Main.main(main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: javax.net.ssl.SSLException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:596)
	at sun.security.ssl.InputRecord.read(InputRecord.java:532)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3393)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.read1(BufferedReader.java:212)
	at java.io.BufferedReader.read(BufferedReader.java:286)
	at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:825)
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:1045)
	at com.google.gson.stream.JsonReader.nextValue(JsonReader.java:784)
	at com.google.gson.stream.JsonReader.objectValue(JsonReader.java:766)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:380)
	at com.google.gson.stream.JsonReader.advance(JsonReader.java:426)
	at com.google.gson.stream.JsonReader.skipValue(JsonReader.java:637)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:170)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
	at com.google.gson.Gson.fromJson(Gson.java:795)
	at com.google.gson.Gson.fromJson(Gson.java:761)
	at org.eclipse.egit.github.core.client.GitHubClient.parseJson(GitHubClient.java:422)
	at org.eclipse.egit.github.core.client.GitHubClient.getBody(GitHubClient.java:529)
	at org.eclipse.egit.github.core.client.GitHubClient.get(GitHubClient.java:736)
	at org.eclipse.egit.github.core.client.PageIterator.next(PageIterator.java:173)
	at org.eclipse.egit.github.core.service.GitHubService.getAll(GitHubService.java:151)
	at org.eclipse.egit.github.core.service.UserService.getFollowing(UserService.java:301)
	at github.Github.getFollowees(github.scala:37)
	at github.GithubNetwork$$anonfun$InitEdges$1.apply(githubnetwork.scala:115)
	at github.GithubNetwork$$anonfun$InitEdges$1.apply(githubnetwork.scala:109)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
	at github.GithubNetwork.InitEdges(githubnetwork.scala:109)
	at Main$.main(main.scala:27)
	at Main.main(main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
```

or

```
[error] (run-main-0) javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1002)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:846)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1484)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1482)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1481)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at org.eclipse.egit.github.core.client.GitHubClient.get(GitHubClient.java:733)
	at org.eclipse.egit.github.core.client.PageIterator.next(PageIterator.java:173)
	at org.eclipse.egit.github.core.service.GitHubService.getAll(GitHubService.java:151)
	at org.eclipse.egit.github.core.service.UserService.getFollowing(UserService.java:301)
	at github.Github.getFollowees(github.scala:37)
	at github.GithubNetwork$$anonfun$InitEdges$1.apply(githubnetwork.scala:115)
	at github.GithubNetwork$$anonfun$InitEdges$1.apply(githubnetwork.scala:109)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
	at github.GithubNetwork.InitEdges(githubnetwork.scala:109)
	at Main$.main(main.scala:27)
	at Main.main(main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(InputRecord.java:505)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:846)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1484)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1482)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1481)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at org.eclipse.egit.github.core.client.GitHubClient.get(GitHubClient.java:733)
	at org.eclipse.egit.github.core.client.PageIterator.next(PageIterator.java:173)
	at org.eclipse.egit.github.core.service.GitHubService.getAll(GitHubService.java:151)
	at org.eclipse.egit.github.core.service.UserService.getFollowing(UserService.java:301)
	at github.Github.getFollowees(github.scala:37)
	at github.GithubNetwork$$anonfun$InitEdges$1.apply(githubnetwork.scala:115)
	at github.GithubNetwork$$anonfun$InitEdges$1.apply(githubnetwork.scala:109)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
	at github.GithubNetwork.InitEdges(githubnetwork.scala:109)
	at Main$.main(main.scala:27)
	at Main.main(main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
```

I run it no less than five times, up to the 180th.


Is it ok?

**Comment by gaocegege** [comment]
Maybe you could open your VPN and have a try again.

**Comment by yangwenmai** [comment]
I will try.

**Comment by yangwenmai** [comment]
VPN is set up, still reporting error

```
[error] (run-main-0) java.io.IOException: Parse exception converting JSON to object
```

**Comment by gaocegege** [comment]
What is your version of scala and sbt?

**Comment by yangwenmai** [comment]
- `Scala code runner version 2.12.6 -- Copyright 2002-2018, LAMP/EPFL and Lightbend, Inc.`
- `sbt.version to 0.13.17`

**Comment by yangwenmai** [comment]
It will work but it will break.
